name: V50 RiceDroid old
on:
  workflow_dispatch
  
concurrency:
  group: ${{  github.ref }}
  cancel-in-progress: true

jobs:
  Repo_git:
    runs-on: self-hosted
    steps:
      - name: Setup git and install repo
        run: |
          git config --global user.email "hmtheboy154@blissos.org"
          git config --global user.name "Konadev"
          git config --global pull.rebase true  
          sudo apt-get update -y && sudo apt-get install repo -y
          
  depends:
    runs-on: self-hosted
    steps:
      - name: Install requirerd dependencies
        run: sudo apt-get install git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip openssl libssl-dev fontconfig -y
        
  Device_tree:
    runs-on: self-hosted
    needs: Repo_git
    steps:
      - name: Clone Device Tree
        run: git clone https://github.com/hmtheboy154/android_device_lge_flashlmdd -b staging/lineage-21 device/lge/flashlmdd || ( cd device/lge/flashlmdd && git fetch && git pull )
        
  Vendor_tree:
    runs-on: self-hosted
    needs: Repo_git
    steps:
      - name: Clone Vendor Tree
        run: git clone https://github.com/lge-sm8150/proprietary_vendor_lge_flashlmdd -b lineage-20 vendor/lge/flashlmdd || ( cd vendor/lge/flashlmdd && git fetch && git pull )
      
  Kernel_tree:
    runs-on: self-hosted
    needs: Repo_git
    steps:
      - name: Clone Kernel Tree
        run: git clone https://github.com/GhostMaster69-dev/android_kernel_xiaomi_vince -b master kernel/xiaomi/vince || ( cd kernel/xiaomi/vince && git fetch && git pull )
      
  Clang:
    runs-on: self-hosted
    needs: Repo_git
    steps:
      - name: Fetch clang
        run: git clone --depth=1 https://gitlab.com/anandhan07/aosp-clang.git -b clang-15.0.3 prebuilts/clang/host/linux-x86/clang-r468909b || ( cd prebuilts/clang/host/linux-x86/clang-r468909b && git fetch && git pull )
  
  Setup_source:
    runs-on: self-hosted
    needs: [Repo_git]
    steps:
      - name: Setup source
        run: repo init --depth=1 --no-repo-verify -u https://github.com/ricedroidOSS/android -b thirteen -g default,-mips,-darwin,-notdefault || echo "Already done"
        
  Sync_source:
    runs-on: self-hosted
    needs: Setup_source
    steps:
      - name: Delete existing builds folders
        run: rm -rf out/target/product/flashlmdd || echo "Doesn't exist"
        
      - name: Sync source
        run: repo sync -c --no-clone-bundle --force-remove-dirty --optimized-fetch --prune --force-sync -j8
        
  Build_rom_vanilla:
    runs-on: self-hosted
    needs: [Sync_source, depends, Clang, Device_tree, Vendor_tree, Kernel_tree, FMRadio, Viper]
    steps:
      - name: Build Vanilla
        run: . build/envsetup.sh && lunch lineage_vince-user && mka bacon | tee log.txt
        
  Build_rom_gapps:
    runs-on: self-hosted
    needs: Build_rom_vanilla
    steps:
      - name: Build Gapps
        run: . build/envsetup.sh && lunch lineage_vince-user && export WITH_GMS=true && mka bacon | tee log.txt
        
  Release:
    runs-on: self-hosted
    needs: [Build_rom_vanilla, Build_rom_gapps]
    steps:
        - name: Prepare tag
          id: tag_code
          run: echo "TAG=$(date +'v%d-%m-%Y-%H%M%S')" >> $GITHUB_OUTPUT
          
        - name: Upload modules to release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.RELEASE_TOKEN }}
            repo_name: rom-builder/Vince-RiceDroid
            tag: ${{ steps.tag_code.outputs.TAG }}
            release_name: ${{ steps.tag_code.outputs.TAG }}
            file_glob: true
            file: out/target/product/vince/riceDroid*
